<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Scry.Sdk\Scry.Sdk.csproj" />
    <ProjectReference Include="..\..\src\Scry.Wpf\Scry.Wpf.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(ScryModernWindowsTargetFramework)</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
