<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Scry.Endpoint\Scry.Endpoint.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFrameworks>$(ScryLibraryTargetFrameworks)</TargetFrameworks>
    <AssemblyName>Scry.Injector.Payload</AssemblyName>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>
