<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Scry.Endpoint\Scry.Endpoint.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>$(ScryLibraryTargetFrameworks)</TargetFrameworks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>
