<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Scry.Contracts\Scry.Contracts.csproj" />
    <ProjectReference Include="..\Scry.Sdk\Scry.Sdk.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>scry</AssemblyName>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>scry</ToolCommandName>
    <PackageId>Scry.Cli</PackageId>
  </PropertyGroup>

</Project>
