<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Scry.Sdk\Scry.Sdk.csproj" />
    <ProjectReference Include="..\..\src\Scry.WinForms\Scry.WinForms.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(ScryModernWindowsTargetFramework)</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

</Project>
